/* automatically generated by rust-bindgen 0.73.2 */

pub const xltypeNum: u32 = 1;
pub const xltypeStr: u32 = 2;
pub const xltypeBool: u32 = 4;
pub const xltypeErr: u32 = 16;
pub const xltypeMulti: u32 = 64;
pub const xltypeMissing: u32 = 128;
pub const xltypeNil: u32 = 256;
pub const xltypeInt: u32 = 2048;
pub const xlbitXLFree: u32 = 4096;
pub const xlbitDLLFree: u32 = 16384;
pub const xlerrNull: u32 = 0;
pub const xlerrNA: u32 = 42;
pub const xlretSuccess: u32 = 0;
pub const xlretFailed: u32 = 32;
pub const xlSpecial: u32 = 16384;
pub const xlFree: u32 = 16384;
pub const xlCoerce: u32 = 16386;
pub const xlGetHwnd: u32 = 16392;
pub const xlGetName: u32 = 16393;
pub const xlGetBinaryName: u32 = 16397;
pub const xlAsyncReturn: u32 = 16400;
pub const xlGetInstPtr: u32 = 16403;
pub const xlfRegister: u32 = 149;
pub const xlfUnregister: u32 = 201;
pub type HANDLE = *mut ::std::os::raw::c_void;
pub type BYTE = ::std::os::raw::c_uchar;
pub type WORD = ::std::os::raw::c_ushort;
pub type INT32 = ::std::os::raw::c_int;
pub type DWORD = ::std::os::raw::c_ulong;
pub type DWORD_PTR = ::std::os::raw::c_ulonglong;
pub type WCHAR = ::std::os::raw::c_ushort;
pub type BOOL = INT32;
pub type XCHAR = WCHAR;
pub type RW = INT32;
pub type COL = INT32;
pub type IDSHEET = DWORD_PTR;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct xlref12 {
    pub rwFirst: RW,
    pub rwLast: RW,
    pub colFirst: COL,
    pub colLast: COL,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of xlref12"][::std::mem::size_of::<xlref12>() - 16usize];
    ["Alignment of xlref12"][::std::mem::align_of::<xlref12>() - 4usize];
    ["Offset of field: xlref12::rwFirst"][::std::mem::offset_of!(xlref12, rwFirst) - 0usize];
    ["Offset of field: xlref12::rwLast"][::std::mem::offset_of!(xlref12, rwLast) - 4usize];
    ["Offset of field: xlref12::colFirst"][::std::mem::offset_of!(xlref12, colFirst) - 8usize];
    ["Offset of field: xlref12::colLast"][::std::mem::offset_of!(xlref12, colLast) - 12usize];
};
pub type XLREF12 = xlref12;
pub type LPXLREF12 = *mut xlref12;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct xlmref12 {
    pub count: WORD,
    pub reftbl: [XLREF12; 1usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of xlmref12"][::std::mem::size_of::<xlmref12>() - 20usize];
    ["Alignment of xlmref12"][::std::mem::align_of::<xlmref12>() - 4usize];
    ["Offset of field: xlmref12::count"][::std::mem::offset_of!(xlmref12, count) - 0usize];
    ["Offset of field: xlmref12::reftbl"][::std::mem::offset_of!(xlmref12, reftbl) - 4usize];
};
pub type XLMREF12 = xlmref12;
pub type LPXLMREF12 = *mut xlmref12;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct xloper12 {
    pub val: xloper12__bindgen_ty_1,
    pub xltype: DWORD,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union xloper12__bindgen_ty_1 {
    pub num: f64,
    pub str_: *mut XCHAR,
    pub xbool: BOOL,
    pub err: ::std::os::raw::c_int,
    pub w: ::std::os::raw::c_int,
    pub sref: xloper12__bindgen_ty_1__bindgen_ty_1,
    pub mref: xloper12__bindgen_ty_1__bindgen_ty_2,
    pub array: xloper12__bindgen_ty_1__bindgen_ty_3,
    pub flow: xloper12__bindgen_ty_1__bindgen_ty_4,
    pub bigdata: xloper12__bindgen_ty_1__bindgen_ty_5,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct xloper12__bindgen_ty_1__bindgen_ty_1 {
    pub count: WORD,
    pub ref_: XLREF12,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of xloper12__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::size_of::<xloper12__bindgen_ty_1__bindgen_ty_1>() - 20usize];
    ["Alignment of xloper12__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<xloper12__bindgen_ty_1__bindgen_ty_1>() - 4usize];
    ["Offset of field: xloper12__bindgen_ty_1__bindgen_ty_1::count"]
        [::std::mem::offset_of!(xloper12__bindgen_ty_1__bindgen_ty_1, count) - 0usize];
    ["Offset of field: xloper12__bindgen_ty_1__bindgen_ty_1::ref_"]
        [::std::mem::offset_of!(xloper12__bindgen_ty_1__bindgen_ty_1, ref_) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct xloper12__bindgen_ty_1__bindgen_ty_2 {
    pub lpmref: *mut XLMREF12,
    pub idSheet: IDSHEET,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of xloper12__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::size_of::<xloper12__bindgen_ty_1__bindgen_ty_2>() - 16usize];
    ["Alignment of xloper12__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::align_of::<xloper12__bindgen_ty_1__bindgen_ty_2>() - 8usize];
    ["Offset of field: xloper12__bindgen_ty_1__bindgen_ty_2::lpmref"]
        [::std::mem::offset_of!(xloper12__bindgen_ty_1__bindgen_ty_2, lpmref) - 0usize];
    ["Offset of field: xloper12__bindgen_ty_1__bindgen_ty_2::idSheet"]
        [::std::mem::offset_of!(xloper12__bindgen_ty_1__bindgen_ty_2, idSheet) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct xloper12__bindgen_ty_1__bindgen_ty_3 {
    pub lparray: *mut xloper12,
    pub rows: RW,
    pub columns: COL,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of xloper12__bindgen_ty_1__bindgen_ty_3"]
        [::std::mem::size_of::<xloper12__bindgen_ty_1__bindgen_ty_3>() - 16usize];
    ["Alignment of xloper12__bindgen_ty_1__bindgen_ty_3"]
        [::std::mem::align_of::<xloper12__bindgen_ty_1__bindgen_ty_3>() - 8usize];
    ["Offset of field: xloper12__bindgen_ty_1__bindgen_ty_3::lparray"]
        [::std::mem::offset_of!(xloper12__bindgen_ty_1__bindgen_ty_3, lparray) - 0usize];
    ["Offset of field: xloper12__bindgen_ty_1__bindgen_ty_3::rows"]
        [::std::mem::offset_of!(xloper12__bindgen_ty_1__bindgen_ty_3, rows) - 8usize];
    ["Offset of field: xloper12__bindgen_ty_1__bindgen_ty_3::columns"]
        [::std::mem::offset_of!(xloper12__bindgen_ty_1__bindgen_ty_3, columns) - 12usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct xloper12__bindgen_ty_1__bindgen_ty_4 {
    pub valflow: xloper12__bindgen_ty_1__bindgen_ty_4__bindgen_ty_1,
    pub rw: RW,
    pub col: COL,
    pub xlflow: BYTE,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union xloper12__bindgen_ty_1__bindgen_ty_4__bindgen_ty_1 {
    pub level: ::std::os::raw::c_int,
    pub tbctrl: ::std::os::raw::c_int,
    pub idSheet: IDSHEET,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of xloper12__bindgen_ty_1__bindgen_ty_4__bindgen_ty_1"]
        [::std::mem::size_of::<xloper12__bindgen_ty_1__bindgen_ty_4__bindgen_ty_1>() - 8usize];
    ["Alignment of xloper12__bindgen_ty_1__bindgen_ty_4__bindgen_ty_1"]
        [::std::mem::align_of::<xloper12__bindgen_ty_1__bindgen_ty_4__bindgen_ty_1>() - 8usize];
    ["Offset of field: xloper12__bindgen_ty_1__bindgen_ty_4__bindgen_ty_1::level"][::std::mem::offset_of!(
        xloper12__bindgen_ty_1__bindgen_ty_4__bindgen_ty_1,
        level
    ) - 0usize];
    ["Offset of field: xloper12__bindgen_ty_1__bindgen_ty_4__bindgen_ty_1::tbctrl"][::std::mem::offset_of!(
        xloper12__bindgen_ty_1__bindgen_ty_4__bindgen_ty_1,
        tbctrl
    ) - 0usize];
    ["Offset of field: xloper12__bindgen_ty_1__bindgen_ty_4__bindgen_ty_1::idSheet"][::std::mem::offset_of!(
        xloper12__bindgen_ty_1__bindgen_ty_4__bindgen_ty_1,
        idSheet
    ) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of xloper12__bindgen_ty_1__bindgen_ty_4"]
        [::std::mem::size_of::<xloper12__bindgen_ty_1__bindgen_ty_4>() - 24usize];
    ["Alignment of xloper12__bindgen_ty_1__bindgen_ty_4"]
        [::std::mem::align_of::<xloper12__bindgen_ty_1__bindgen_ty_4>() - 8usize];
    ["Offset of field: xloper12__bindgen_ty_1__bindgen_ty_4::valflow"]
        [::std::mem::offset_of!(xloper12__bindgen_ty_1__bindgen_ty_4, valflow) - 0usize];
    ["Offset of field: xloper12__bindgen_ty_1__bindgen_ty_4::rw"]
        [::std::mem::offset_of!(xloper12__bindgen_ty_1__bindgen_ty_4, rw) - 8usize];
    ["Offset of field: xloper12__bindgen_ty_1__bindgen_ty_4::col"]
        [::std::mem::offset_of!(xloper12__bindgen_ty_1__bindgen_ty_4, col) - 12usize];
    ["Offset of field: xloper12__bindgen_ty_1__bindgen_ty_4::xlflow"]
        [::std::mem::offset_of!(xloper12__bindgen_ty_1__bindgen_ty_4, xlflow) - 16usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct xloper12__bindgen_ty_1__bindgen_ty_5 {
    pub h: xloper12__bindgen_ty_1__bindgen_ty_5__bindgen_ty_1,
    pub cbData: ::std::os::raw::c_long,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union xloper12__bindgen_ty_1__bindgen_ty_5__bindgen_ty_1 {
    pub lpbData: *mut BYTE,
    pub hdata: HANDLE,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of xloper12__bindgen_ty_1__bindgen_ty_5__bindgen_ty_1"]
        [::std::mem::size_of::<xloper12__bindgen_ty_1__bindgen_ty_5__bindgen_ty_1>() - 8usize];
    ["Alignment of xloper12__bindgen_ty_1__bindgen_ty_5__bindgen_ty_1"]
        [::std::mem::align_of::<xloper12__bindgen_ty_1__bindgen_ty_5__bindgen_ty_1>() - 8usize];
    ["Offset of field: xloper12__bindgen_ty_1__bindgen_ty_5__bindgen_ty_1::lpbData"][::std::mem::offset_of!(
        xloper12__bindgen_ty_1__bindgen_ty_5__bindgen_ty_1,
        lpbData
    ) - 0usize];
    ["Offset of field: xloper12__bindgen_ty_1__bindgen_ty_5__bindgen_ty_1::hdata"][::std::mem::offset_of!(
        xloper12__bindgen_ty_1__bindgen_ty_5__bindgen_ty_1,
        hdata
    ) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of xloper12__bindgen_ty_1__bindgen_ty_5"]
        [::std::mem::size_of::<xloper12__bindgen_ty_1__bindgen_ty_5>() - 16usize];
    ["Alignment of xloper12__bindgen_ty_1__bindgen_ty_5"]
        [::std::mem::align_of::<xloper12__bindgen_ty_1__bindgen_ty_5>() - 8usize];
    ["Offset of field: xloper12__bindgen_ty_1__bindgen_ty_5::h"]
        [::std::mem::offset_of!(xloper12__bindgen_ty_1__bindgen_ty_5, h) - 0usize];
    ["Offset of field: xloper12__bindgen_ty_1__bindgen_ty_5::cbData"]
        [::std::mem::offset_of!(xloper12__bindgen_ty_1__bindgen_ty_5, cbData) - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of xloper12__bindgen_ty_1"][::std::mem::size_of::<xloper12__bindgen_ty_1>() - 24usize];
    ["Alignment of xloper12__bindgen_ty_1"]
        [::std::mem::align_of::<xloper12__bindgen_ty_1>() - 8usize];
    ["Offset of field: xloper12__bindgen_ty_1::num"]
        [::std::mem::offset_of!(xloper12__bindgen_ty_1, num) - 0usize];
    ["Offset of field: xloper12__bindgen_ty_1::str_"]
        [::std::mem::offset_of!(xloper12__bindgen_ty_1, str_) - 0usize];
    ["Offset of field: xloper12__bindgen_ty_1::xbool"]
        [::std::mem::offset_of!(xloper12__bindgen_ty_1, xbool) - 0usize];
    ["Offset of field: xloper12__bindgen_ty_1::err"]
        [::std::mem::offset_of!(xloper12__bindgen_ty_1, err) - 0usize];
    ["Offset of field: xloper12__bindgen_ty_1::w"]
        [::std::mem::offset_of!(xloper12__bindgen_ty_1, w) - 0usize];
    ["Offset of field: xloper12__bindgen_ty_1::sref"]
        [::std::mem::offset_of!(xloper12__bindgen_ty_1, sref) - 0usize];
    ["Offset of field: xloper12__bindgen_ty_1::mref"]
        [::std::mem::offset_of!(xloper12__bindgen_ty_1, mref) - 0usize];
    ["Offset of field: xloper12__bindgen_ty_1::array"]
        [::std::mem::offset_of!(xloper12__bindgen_ty_1, array) - 0usize];
    ["Offset of field: xloper12__bindgen_ty_1::flow"]
        [::std::mem::offset_of!(xloper12__bindgen_ty_1, flow) - 0usize];
    ["Offset of field: xloper12__bindgen_ty_1::bigdata"]
        [::std::mem::offset_of!(xloper12__bindgen_ty_1, bigdata) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of xloper12"][::std::mem::size_of::<xloper12>() - 32usize];
    ["Alignment of xloper12"][::std::mem::align_of::<xloper12>() - 8usize];
    ["Offset of field: xloper12::val"][::std::mem::offset_of!(xloper12, val) - 0usize];
    ["Offset of field: xloper12::xltype"][::std::mem::offset_of!(xloper12, xltype) - 24usize];
};
pub type XLOPER12 = xloper12;
pub type LPXLOPER12 = *mut xloper12;
unsafe extern "C" {
    pub fn Excel12(
        xlfn: ::std::os::raw::c_int,
        operRes: LPXLOPER12,
        count: ::std::os::raw::c_int,
        ...
    ) -> ::std::os::raw::c_int;
}
